import type { SmartToolEntry } from './smartToolsCatalog';

export const SMART_TOOLS_CATALOG_5: readonly SmartToolEntry[] = [
  { toolId: 'mrx.tool.020-genetic-potential', slug: 'tool-020-genetic-potential', href: '/smarttools/tool-020-genetic-potential', order: 360, titleEn: 'Genetic Potential Calculator', titleAr: 'حاسبة القدرة الوراثية', descriptionEn: 'Training potential estimator', descriptionAr: 'مقدر القدرة التدريبية', icon: 'Dna', accessTier: 'free', componentPath: '@/components/tools/tool-020-genetic-potential', enginePath: 'lib/tools/engines/tool-020-genetic-potential', schemaPath: 'lib/tools/schemas/tool-020-genetic-potential' },
  { toolId: 'mrx.tool.021-peptide-protocol', slug: 'tool-021-peptide-protocol', href: '/smarttools/tool-021-peptide-protocol', order: 370, titleEn: 'Peptide Protocol Planner', titleAr: 'مخطط بروتوكول الببتيد', descriptionEn: 'Peptide dosing and scheduling', descriptionAr: 'جرعات الببتيد وجدولتها', icon: 'Syringe', accessTier: 'free', componentPath: '@/components/tools/tool-021-peptide-protocol', enginePath: 'lib/tools/engines/tool-021-peptide-protocol', schemaPath: 'lib/tools/schemas/tool-021-peptide-protocol' },
  { toolId: 'mrx.tool.022-half-life-stacker', slug: 'tool-022-half-life-stacker', href: '/smarttools/tool-022-half-life-stacker', order: 380, titleEn: 'Half-Life Stacker', titleAr: 'مركب نصف العمر', descriptionEn: 'Multi-ester stack timing', descriptionAr: 'توقيت حزمة الإسترات', icon: 'Timer', accessTier: 'free', componentPath: '@/components/tools/tool-022-half-life-stacker', enginePath: 'lib/tools/engines/tool-022-half-life-stacker', schemaPath: 'lib/tools/schemas/tool-022-half-life-stacker' },
  { toolId: 'mrx.tool.023-trt-optimization', slug: 'tool-023-trt-optimization', href: '/smarttools/tool-023-trt-optimization', order: 390, titleEn: 'TRT Optimization', titleAr: 'تحسين TRT', descriptionEn: 'TRT dosing optimization', descriptionAr: 'تحسين جرعات TRT', icon: 'Beaker', accessTier: 'free', componentPath: '@/components/tools/tool-023-trt-optimization', enginePath: 'lib/tools/engines/tool-023-trt-optimization', schemaPath: 'lib/tools/schemas/tool-023-trt-optimization' },
  { toolId: 'mrx.tool.024-bloodwork-interpreter', slug: 'tool-024-bloodwork-interpreter', href: '/smarttools/tool-024-bloodwork-interpreter', order: 400, titleEn: 'Bloodwork Interpreter', titleAr: 'مفسر الفحوصات', descriptionEn: 'Post-cycle recovery interpretation', descriptionAr: 'تفسير استعادة ما بعد الدورة', icon: 'Beaker', accessTier: 'free', componentPath: '@/components/tools/tool-024-bloodwork-interpreter', enginePath: 'lib/tools/engines/tool-024-bloodwork-interpreter', schemaPath: 'lib/tools/schemas/tool-024-bloodwork-interpreter' },
  { toolId: 'mrx.tool.025-drug-interaction-pro', slug: 'tool-025-drug-interaction-pro', href: '/smarttools/tool-025-drug-interaction-pro', order: 410, titleEn: 'Drug Interaction Pro', titleAr: 'فاحص التفاعلات الاحترافي', descriptionEn: 'Advanced interaction analysis', descriptionAr: 'تحليل تفاعلات متقدم', icon: 'Beaker', accessTier: 'free', componentPath: '@/components/tools/tool-025-drug-interaction-pro', enginePath: 'lib/tools/engines/tool-025-drug-interaction-pro', schemaPath: 'lib/tools/schemas/tool-025-drug-interaction-pro' },
  { toolId: 'mrx.tool.026-injection-pain', slug: 'tool-026-injection-pain', href: '/smarttools/tool-026-injection-pain', order: 420, titleEn: 'Injection Pain Minimizer', titleAr: 'مقلل ألم الحقن', descriptionEn: 'Comfort and rotation planner', descriptionAr: 'مخطط الراحة والتدوير', icon: 'Syringe', accessTier: 'free', componentPath: '@/components/tools/tool-026-injection-pain', enginePath: 'lib/tools/engines/tool-026-injection-pain', schemaPath: 'lib/tools/schemas/tool-026-injection-pain' },
  { toolId: 'mrx.tool.027-ester-conversion', slug: 'tool-027-ester-conversion', href: '/smarttools/tool-027-ester-conversion', order: 430, titleEn: 'Ester Conversion', titleAr: 'تحويل الإستر', descriptionEn: 'Base hormone equivalence calculator', descriptionAr: 'حاسبة مكافئ الهرمون الأساسي', icon: 'Calculator', accessTier: 'free', componentPath: '@/components/tools/tool-027-ester-conversion', enginePath: 'lib/tools/engines/tool-027-ester-conversion', schemaPath: 'lib/tools/schemas/tool-027-ester-conversion' },
  { toolId: 'mrx.tool.028-stacking-synergy', slug: 'tool-028-stacking-synergy', href: '/smarttools/tool-028-stacking-synergy', order: 440, titleEn: 'Stacking Synergy', titleAr: 'تآزر الحزم', descriptionEn: 'Stack compatibility scoring', descriptionAr: 'تقييم توافق الحزم', icon: 'Calculator', accessTier: 'free', componentPath: '@/components/tools/tool-028-stacking-synergy', enginePath: 'lib/tools/engines/tool-028-stacking-synergy', schemaPath: 'lib/tools/schemas/tool-028-stacking-synergy' },
  { toolId: 'mrx.tool.029-side-effect-warning', slug: 'tool-029-side-effect-early-warning', href: '/smarttools/tool-029-side-effect-early-warning', order: 450, titleEn: 'Side Effect Early Warning', titleAr: 'الإنذار المبكر', descriptionEn: 'Predictive symptom analyzer', descriptionAr: 'محلل الأعراض التنبؤي', icon: 'Scale', accessTier: 'free', componentPath: '@/components/tools/tool-029-side-effect-early-warning', enginePath: 'lib/tools/engines/tool-029-side-effect-early-warning', schemaPath: 'lib/tools/schemas/tool-029-side-effect-early-warning' },
  { toolId: 'mrx.tool.030-cycle-cost', slug: 'tool-030-cycle-cost-calculator', href: '/smarttools/tool-030-cycle-cost-calculator', order: 460, titleEn: 'Cycle Cost Calculator', titleAr: 'حاسبة تكلفة الدورة', descriptionEn: 'Financial planning for cycles', descriptionAr: 'التخطيط المالي للدورات', icon: 'Calculator', accessTier: 'free', componentPath: '@/components/tools/tool-030-cycle-cost-calculator', enginePath: 'lib/tools/engines/tool-030-cycle-cost-calculator', schemaPath: 'lib/tools/schemas/tool-030-cycle-cost-calculator' },
];