import type { SmartToolEntry } from './smartToolsCatalog';

export const SMART_TOOLS_CATALOG_3: readonly SmartToolEntry[] = [
  { toolId: 'mrx.tool.008-side-effect-tracker', slug: 'tool-008-side-effect-tracker', href: '/smarttools/tool-008-side-effect-tracker', order: 220, titleEn: 'Side Effect Tracker', titleAr: 'متتبع الآثار الجانبية', descriptionEn: 'Track cycle side effects', descriptionAr: 'تتبع الآثار الجانبية', icon: 'Scale', accessTier: 'free', componentPath: '@/components/tools/tool-008-side-effect-tracker', enginePath: 'lib/tools/engines/tool-008-side-effect-tracker', schemaPath: 'lib/tools/schemas/tool-008-side-effect-tracker' },
  { toolId: 'mrx.tool.009-injection-site-rotator', slug: 'tool-009-injection-site-rotator', href: '/smarttools/tool-009-injection-site-rotator', order: 230, titleEn: 'Injection Site Rotator', titleAr: 'مدور مواقع الحقن', descriptionEn: 'Rotation planner for sites', descriptionAr: 'مخطط تدوير المواقع', icon: 'Syringe', accessTier: 'free', componentPath: '@/components/tools/tool-009-injection-site-rotator', enginePath: 'lib/tools/engines/tool-009-injection-site-rotator', schemaPath: 'lib/tools/schemas/tool-009-injection-site-rotator' },
  { toolId: 'mrx.tool.010-compound-stack-builder', slug: 'tool-010-compound-stack-builder', href: '/smarttools/tool-010-compound-stack-builder', order: 240, titleEn: 'Compound Stack Builder', titleAr: 'بناء حزمة المركبات', descriptionEn: 'Build stacks with synergy scoring', descriptionAr: 'ابن الحزم مع تقييم التآزر', icon: 'Calculator', accessTier: 'free', componentPath: '@/components/tools/tool-010-compound-stack-builder', enginePath: 'lib/tools/engines/tool-010-compound-stack-builder', schemaPath: 'lib/tools/schemas/tool-010-compound-stack-builder' },
  { toolId: 'mrx.tool.011-progress-tracker', slug: 'tool-011-progress-tracker', href: '/smarttools/tool-011-progress-tracker', order: 250, titleEn: 'Progress Tracker', titleAr: 'متتبع التقدم', descriptionEn: 'Track training and body progress', descriptionAr: 'تتبع التدريب والجسم', icon: 'Scale', accessTier: 'free', componentPath: '@/components/tools/tool-011-progress-tracker', enginePath: 'lib/tools/engines/tool-011-progress-tracker', schemaPath: 'lib/tools/schemas/tool-011-progress-tracker' },
  { toolId: 'mrx.tool.012-calorie-adjuster', slug: 'tool-012-calorie-adjuster', href: '/smarttools/tool-012-calorie-adjuster', order: 260, titleEn: 'Calorie Adjuster', titleAr: 'معدل السعرات', descriptionEn: 'Adjust calories by phase', descriptionAr: 'اضبط السعرات حسب المرحلة', icon: 'Flame', accessTier: 'free', componentPath: '@/components/tools/tool-012-calorie-adjuster', enginePath: 'lib/tools/engines/tool-012-calorie-adjuster', schemaPath: 'lib/tools/schemas/tool-012-calorie-adjuster' },
  { toolId: 'mrx.tool.013-macro-optimizer', slug: 'tool-013-macro-optimizer', href: '/smarttools/tool-013-macro-optimizer', order: 270, titleEn: 'Macro Optimizer', titleAr: 'محسن الماكروز', descriptionEn: 'Optimize protein/carbs/fats', descriptionAr: 'حسن تقسيم الماكروز', icon: 'Flame', accessTier: 'free', componentPath: '@/components/tools/tool-013-macro-optimizer', enginePath: 'lib/tools/engines/tool-013-macro-optimizer', schemaPath: 'lib/tools/schemas/tool-013-macro-optimizer' },
  { toolId: 'mrx.tool.014-water-retention', slug: 'tool-014-water-retention', href: '/smarttools/tool-014-water-retention', order: 280, titleEn: 'Water Retention Assessor', titleAr: 'مقيم احتباس الماء', descriptionEn: 'Assess water retention drivers', descriptionAr: 'قيم مسببات احتباس الماء', icon: 'Beaker', accessTier: 'free', componentPath: '@/components/tools/tool-014-water-retention', enginePath: 'lib/tools/engines/tool-014-water-retention', schemaPath: 'lib/tools/schemas/tool-014-water-retention' },
  { toolId: 'mrx.tool.015-shbg-modulator', slug: 'tool-015-shbg-modulator', href: '/smarttools/tool-015-shbg-modulator', order: 290, titleEn: 'SHBG Modulator', titleAr: 'منظم SHBG', descriptionEn: 'Estimate free hormone modulation', descriptionAr: 'قدر تعديل الهرمونات الحرة', icon: 'Dna', accessTier: 'free', componentPath: '@/components/tools/tool-015-shbg-modulator', enginePath: 'lib/tools/engines/tool-015-shbg-modulator', schemaPath: 'lib/tools/schemas/tool-015-shbg-modulator' },
];